{% set name = "apispec" %}
{% set version = "0.21.0" %}
{% set sha256 = "5ca0fb665dac85b2548aad209b82fd4ebeb38a87fc6aab7e0a3987f75ca15e1c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pyyaml >=3.10

test:
  imports:
    - apispec

about:
  home: https://github.com/marshmallow-code/apispec
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A pluggable API specification generator'

  description: |
    A pluggable API specification generator. Currently supports the OpenAPI
    specification (f.k.a. Swagger 2.0).
  doc_url: http://apispec.readthedocs.io/
  dev_url: https://github.com/marshmallow-code/apispec

extra:
  recipe-maintainers:
    - frol
