{% set name = "apispec" %}
{% set version = "6.10.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0a888555cd4aa5fb7176041be15684154fd8961055e1672e703abf737e8761bf

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - flit-core <4
  run:
    - python
    - packaging >=21.3
  run_constrained:
    - pyyaml >=3.10
    - marshmallow >=3.18.0

test:
  source_files:
    - tests
  imports:
    - apispec
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests
  requires:
    - pip
    - pytest
    - marshmallow
    - pyyaml
    - openapi-spec-validator
    - requests

about:
  home: https://github.com/marshmallow-code/apispec
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A pluggable API specification generator
  description: |
    A pluggable API specification generator. Currently supports the OpenAPI
    specification (f.k.a. Swagger 2.0).
  doc_url: https://apispec.readthedocs.io
  dev_url: https://github.com/marshmallow-code/apispec

extra:
  recipe-maintainers:
    - frol
    - rth
    - carlodri
