travis:
  secure:
    BINSTAR_TOKEN: PDJ3rf0kGO8lC6HaPkPba4iCJ8j+1PBBiQcVtvcRnJ+eS8AnH17XsBtEWaPl7sOZHOKZbREAzWXSkmgN2daZhqqXglxk2a+ZRjbbX9hiWIpIo2dNn21uw50LGA7C24mgmQzYVD2MMF6IX87+RBcU0JX74ZFqNqLqm9WaT9k+HH2M6BtXu7gyKdwStAy6D3zqxCYXYLETExMosSADAnXg9iU5JVJFqRGIsKGFK3J3yfRAHNVmAJQnRbglAtsJ3+VNkAs/iRIt3mJVWZEI0j07bx6RRUs+XWP2/ANI11KFFMw0wpxRp5k3nbNw1m89+Cl972tV87pQIm/3DAyLtuEA6DQxwlDMVEf4NOLaReokaYLJk84SRAByj0UQv0IBd5CRAwA2k8VowJ0tMNiLdzDu3Dz2U1fWv/SMJZM/rGpvhF6qxLuuWFa3WJMyN3dFaFpAVW/Plt2dbNh5gy6xU5vw8X+eTqd+wexAMfRquQOS98KEzwdPwGGEawd4PF8sP4WUjPKQ9PvksWWPJrYS6wUk8A1wnoJ3SCs+bxEm+TROYwTPYysEeSFSlg+QAZG82Qk80H99jM33ITV+0HZGfI58MgeoSW2d1Il/Ri5N9Jb1lhMcetyAjM/I3/SJoUo2AMWK6upTD/gflekTYbIxAnuVDjPq9L7NMEbekPRbKqd58+I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
