travis:
  secure:
    BINSTAR_TOKEN: os5I8GghM0G81fQ6vs6t0p/fkMhOH6yTX3xZ58ckny78D/RVv225aGo+gjjCSWMU8TNV7tjA7rbQSh1P0zioxXF/dWZ7+FZ8N8zOwGEiro2Zs41mxFMN8R1CWESvWSuardh4gjN1BW56YPgRq1yB/ZcDL0/EntOFUp+bP9YiyHH724LLHAwxe33ngiPVumCrLQ14kajtOJBlzo3LgtMxGW74eL/Qo625XfnbLcBx+WZ7VMHl6CFmIV9ETlMcG/5CHLIGvitjcWy6b839fo+g1EXFAI6fmfbmL4rUKzii8xeXRzcpvinkXEMOR+oF+acwW1PeZ3gHzDXCRBq4xenNAXB8SXdOb6pPjl06ramOhNvkminqPbb2cqXd9NZ7c8fLQu4sv4J1863p7BpGOkfdi9vc/2z3VrksLxfdLpYcdmayZbA8Mrq/P+jbEOCWpkbrZkwjc2eoQupnPkeDgQJ4Kp7v00aQsrb+v4/GOF7ssr3b8Np7iYx32+J2j17/I77oie6UOIa376G2sU6zEEHpsGas2qhO94aoctEPlSOkYRXnbZLpk/yasOTUWBuK6WmCDiuk81zcYrwPSwHV+lzpg98qAU0Q/3cyQZqUvCjadXNzWx2+UG+btrK8YXKDWXRAEfm/hrozgmP8lVDUcxEYIY6nEFKWfs0lGpeN+Obg+3s=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
