travis:
  secure:
    BINSTAR_TOKEN: WRrJJoLW0z5xxUKJ88MXWuFu7tnGxC6gKRBkcMp/hkwK+GNWwtqZBca+nhZk7Rx+jtoTF6UwguCq6U7PKnuxi0Pk4WwqJq1Ck+rcatvh1qk3BVMUWUkNAUS4isTm2rI4G72L7NPX9jITgNW6xwm9NJllACAiTaSfTX1a2yJDTHRsckKEUP8aaqjLB9h+HQ98XESwUApAF8Cq7doxcUPF6WY0ShD2yLOUz/30JPdnxrTJDtCi9L8m8lcu5AEDJjgF/6GqLXh2F4ZK+50trjMZDCDjF59f0oFb9sJn/qfBjyfLf4aWho/nD2X8TBPero+K74ihUwICPVm5bAcKgccjCbidUabHxWY9TAkUU0DpS8LtylJH0bnQCN8fOdC8NucSEm70XlVYxR4wRas/bvhEHx1AEL9PZxKGB8P1HuyririweblBr81dFxy1UIkiwmv9458CsYtJyQ0xPmBhUlxjLLmw1vZoK05JMb0hQqU2+f2pm8f6d1SYI9DJlZdUp+LAMGT1XfEErpyIRQAj8rbSwzCES9BAYJOv3oYYKbJ7HaG2dEh+xhxxt4ZRTPSuJFmnwlHYeOHn73QjQJ87JW+4Y49FfwS7lvI4lsLVVxEJKWa6rEEbE9t+rWnT1Wg7AhzRiGK2LGAeYPa1ByD+9TjwC53F02SlVus5Ut8oMuGOMbo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
